### ISSUE TITLE
New exception in drag and drop feature

### ISSUE THREAD

**Issue by mackie100** [LeoNatan/LNPropertyListEditor#10]
If drop an item at the end of the outline editor the app crashes.

**Comment by LeoNatan** [comment]
This was fixed already. Make sure to always test on the latest version. Thanks

**Comment by mackie100** [comment]
> This was fixed already. Make sure to always test on the latest version. Thanks

Ok Sorry.

**Comment by LeoNatan** [comment]
No worries

**Comment by mackie100** [comment]
> No worries

Found new bug: if drop an item in the same position, the app hangs. This occurs only if item is a Dictionary or array

**Comment by LeoNatan** [comment]
What do you see in the stack trace?

**Comment by mackie100** [comment]
> What do you see in the stack trace?

Nothing. Beach ball and high cpu usage.

**Comment by LeoNatan** [comment]
Stack trace in Xcode.

**Comment by mackie100** [comment]
> Stack trace in Xcode.

No stack trace. needs to force quit, the system becomes unresponsive.

**Comment by LeoNatan** [comment]
I can’t reproduce. If the entire system becomes unresponsive, I’m not sure it’s an issue with the framework? I meant try pausing in Xcode when the issue occurs, or sample the process using Activity Monitor.

**Comment by mackie100** [comment]
> I can’t reproduce. If the entire system becomes unresponsive, I’m not sure it’s an issue with the framework? I meant try pausing in Xcode when the issue occurs, or sample the process using Activity Monitor.

[sample LNPropertyListEditorExample.txt](https://github.com/LeoNatan/LNPropertyListEditor/files/6436107/sample.LNPropertyListEditorExample.txt)

**Comment by LeoNatan** [comment]
Sorry, not sure what is going on. I can't reproduce. Try master, I just pushed something related to drag/drop moving.
