### ISSUE TITLE
Autosave Expanded Item in PropertyList Editor

### ISSUE THREAD

**Issue by mackie100** [LeoNatan/LNPropertyListEditor#11]
I can't figure out how to expand an item if a node have the same key name.

I can expand the first node "item1->object", but not the second "item2->object" if the first is already expanded. 

This is my working code:
```
-(id)outlineView:(NSOutlineView *)outlineView itemForPersistentObject:(id)object {
    LNPropertyListNode *node = [NSKeyedUnarchiver unarchiveObjectWithData:object];
    return [self itemForNode:node inNodes:[self.rootPropertyListNode children]];
}

-(id)outlineView:(NSOutlineView *)outlineView persistentObjectForItem:(id)item {
    return (LNPropertyListNode*)[NSKeyedArchiver archivedDataWithRootObject:item];
}

-(id)itemForNode:(LNPropertyListNode*)object inNodes:(NSArray*)nodes {
    for (LNPropertyListNode *node in nodes) {
        if ([node.key isEqualToString: object.key]) {
            return node;
        }

        LNPropertyListNode *item = [self itemForNode:object inNodes:node.children];
        if ([item.key isEqualToString:object.key] ) {
            return item;
        }
    }
    return nil;
}
```

Can you help me? Thanks in advance.

**Comment by LeoNatan** [comment]
I’m sorry, I don’t understand the question. There is dedicated API to expand nodes, are you using that? I have no idea what `OCPropertyListNode` is.

**Comment by mackie100** [comment]
> I’m sorry, I don’t understand the question. There is dedicated API to expand nodes, are you using that? I have no idea what `OCPropertyListNode` is.

I need to use auto save expanded item feature, I can't figure out how to expand a node if an item has other nested item with the same name.

![shoot](https://user-images.githubusercontent.com/37126690/118288440-beace380-b4d4-11eb-9816-99eb4e84f637.png)

**Comment by LeoNatan** [comment]
Well, in your code, you are scanning the node hierarchy and stop once you find a node with that key.
```
if ([node.key isEqualToString: object.key]) {
    return node;
}
```
Of course it will only expand the first item with an "Object" key. Your logic is incorrect.

**Comment by LeoNatan** [comment]
You should be using this API:
https://github.com/LeoNatan/LNPropertyListEditor/blob/31191af0afa7c348e7582356a8943b12bf7e2903/LNPropertyListEditor/LNPropertyListEditor/LNPropertyListEditor.h#L140

If you want to expand all items with key "Object", in your method just expand each one, instead of stopping after the first one.

**Comment by mackie100** [comment]
> You should be using this API:
> https://github.com/LeoNatan/LNPropertyListEditor/blob/31191af0afa7c348e7582356a8943b12bf7e2903/LNPropertyListEditor/LNPropertyListEditor/LNPropertyListEditor.h#L140
> 
> If you want to expand all items with key "Object", in your method just expand each one, instead of stopping after the first one.

This isn't a good solution, I need to expand the persistent items only. I need to figure because the function `-(id)itemForNode:(LNPropertyListNode*)object inNodes:(NSArray*)nodes` stopping at the first item instead to expand recursively.

**Comment by LeoNatan** [comment]
I don’t understand what you are saying, sorry. The root node is exposed in the public header, and you write your own traversal algorithm there.

**Comment by mackie100** [comment]
> I don’t understand what you are saying, sorry. The root node is exposed in the public header, and you write your own traversal algorithm there.

I don't need to expand all items but autosaved items when I reopen the plist file.
![Schermata 2021-05-21 alle 16 09 01](https://user-images.githubusercontent.com/37126690/119151248-8155d200-ba4f-11eb-818f-42100ccad3cc.png)

**Comment by LeoNatan** [comment]
So you need to figure an algorithm that will let you serialize all expanded item locations and then expand those. Perhaps you can use NSIndexPath for all expanded items, and use those.

**Comment by mackie100** [comment]
> So you need to figure an algorithm that will let you serialize all expanded item locations and then expand those. Perhaps you can use NSIndexPath for all expanded items, and use those.

I need a data like this `<LNPropertyListNode 0x600002025680 key: “object4” type: “Dictionary” children: “3 items” parentItem:"Item1">` and getting  a value by `node.parentItem` 
It might be an idea.
