### ISSUE TITLE
Crash/Exception when attempting to copy and paste an array/dictionary node

### ISSUE THREAD

**Issue by robfeldmann** [LeoNatan/LNPropertyListEditor#14]
Hey Leo, great job on this library! 

I am creating this issue to document some bugs we've discovered and fixed. We've been living with them for a few weeks now and so I feel comfortable contributing back to this project. An accompanying PR is forthcoming.

ℹ️ Note that resolving the issues below revealed a few other issues. I'll include details about those in the PR.

#### Steps to reproduce:

1. Select a plist node and copy it via ⌘C

#### Observe:

> ***** -[NSKeyedUnarchiver validateAllowedClass:forKey:] allowed unarchiving safe plist type ''NSString' (0x1e1780918) [/System/Library/Frameworks/Foundation.framework]' for key 'key', even though it was not explicitly included in the client allowed classes set: '{(
>     "'LNPropertyListNode' (0x104650df0) [~/Library/Developer/Xcode/DerivedData/LNPropertyListEditorExample-eoszcjiazyaglicebgfeoshkripr/Build/Products/Debug/LNPropertyListEditor.framework]"
> )}'. This will be disallowed in the future.**

#### Steps to reproduce:

1. Select the `testDict`  or `test` array node
2. Copy via ⌘C, then paste via ⌘V

#### Observe:

An exception occurs: `***** -[__NSArrayM insertObject:atIndex:]: object cannot be nil**`. For me the app doesn’t crash, but the state of the editor is inconsistent. For example, attempting to sort by the `key` column results in a blank editor. 🙃 On my colleagues machine, it would crash.

**Comment by LeoNatan** [comment]
Hello,

I am guessing this is a recent thing, where Apple has enabled secure coding by default for `NSKeyedUnarchiver`. Fixing that is easy. After that fix, however, I am unable to reproduce any of the issues you mention here, including copy/pasting arrays and dictionaries, or drag and drop:


https://github.com/LeoNatan/LNPropertyListEditor/assets/2270433/b04569ce-2750-4a5e-bf50-33e2d0a54598

Let me push a fix for the copy/paste issue, and you can test the rest of the functionality.

Thanks

**Comment by LeoNatan** [comment]
Please try using 2.1.4.

**Comment by robfeldmann** [comment]
Awesome. That's a MUCH simpler solution. Thanks for taking a look so quickly. I can confirm this addresses all of the other issues. 👍

**Comment by LeoNatan** [comment]
Thank you for confirming! Happy coding!
