### ISSUE TITLE
Carthage: No tagged versions found for github "LeoNatan/LNPropertyListEditor"

### ISSUE THREAD

**Issue by sebj** [LeoNatan/LNPropertyListEditor#3]
Adding `github "LeoNatan/LNPropertyListEditor"` to my Cartfile as per the README, followed by running `carthage update` gives an error – `No tagged versions found for github "LeoNatan/LNPropertyListEditor"`.

It might be worth either tagging a version of this repo, or noting in the README that adding `github "LeoNatan/LNPropertyListEditor" "master"` to a Cartfile can be used to work around this error and use the latest master.

**Comment by LeoNatan** [comment]
Apologies. Added a release now to make it work.
