### ISSUE TITLE
Programmatically Expand/Collapse All Items in Plist

### ISSUE THREAD

**Issue by JUSTINMKAUFMAN** [LeoNatan/LNPropertyListEditor#4]
First of all, this is a great library! Nice work! 

My only issue is that I'm not seeing a way to automatically expand all the arrays/dictionaries in a LNPropertyListEditor object. Some of the plists I show in my app have a great deal of nesting, and manually expanding each group is quite time consuming.

Any ideas?

**Comment by LeoNatan** [comment]
Thanks for the feedback and kind words!

This would be easy to achieve using the NSOutlineView API. Unfortunately, right now the outline view is [not exposed as public API](https://github.com/LeoNatan/LNPropertyListEditor/blob/39fefcbde4769739dadce7a96ce0653df120d05e/LNPropertyListEditor/LNPropertyListEditor/LNPropertyListEditor-Private.h#L31), but as a workaround, you can KVO the private property, and from there you can use the standard APIs.

```objc
[[_plistEditor valueForKey:@"outlineView"] expandItem:nil expandChildren:YES];
```

As a side note, your users can also do the standard Command+Click on the outline disclosure buttons to expand or collapse the entire hierarchy.

**Comment by LeoNatan** [comment]
I will look to expand the existing API to allow expansion and collapse of nodes. Thank you

**Comment by JUSTINMKAUFMAN** [comment]
Thanks for the quick reply! I will try your idea re: KVO and look forward to seeing where the API goes in the future (also happy to open a PR for this if you’d like).

**Comment by LeoNatan** [comment]
Thanks, that would be lovely.

Was thinking about exposing two more methods for the nodes:
```objc
@property (nonatomic, readonly) LNPropertyListNode* rootPropertyListNode;
- (void)reloadNode:(LNPropertyListNode*)node reloadChildren:(BOOL)reloadChildren;
//
- (void)expandNode:(LNPropertyListNode*)node expandChildren:(BOOL)expandChildren;
- (void)collapseNode:(LNPropertyListNode*)node collapseChildren:(BOOL)collapseChildren;
```

which would forward the node object to the appropriate outline view methods.

**Comment by JUSTINMKAUFMAN** [comment]
I was literally about to suggest adding reload capability. Looks great!

Two more things that might be worth considering:

1. Currently the nodes show up in random order (even when loaded from a plist in which the nodes are alphabetized). And clicking the headers in the UI doesn't seem to sort them like it does in an actual plist. It'd be nice if the API exposed sorting options.

2. Automatic reloading of plist nodes when a change to that node in the underlying plist file occurs outside of your UI.

In addition to allowing users to modify plist contents via your plistEditor view, my application also performs modifications on those plist files programmatically. 

I have user-initiated changes syncing back to the originally loaded file nicely, but external mods are not being reflected in the plistEditor view (unless I reset/reload the file into the view).

If that seems intriguing, [KZFileWatchers](https://github.com/krzysztofzablocki/KZFileWatchers) by @krzysztofzablocki is a handy framework for observing changes to specific files.

Happy to help with one or more of those if they sound good to you (though I'll admit I'm far more proficient with Swift than I am with Obj-C...).

**Comment by LeoNatan** [comment]
There is no sort order because dictionaries have no sort order, but property lists do (even if key-value pairs). Theoretically, it would be great to provide sorting capabilities (including a way to export and import data in a sorted manner for the property list file itself), but not sure how to design that API.

Interesting idea. The framework does not work with files, so using something like `KZFileWatchers` doesn't make sense in this context. What might make sense is using binding with an `NSTreeController`, which would pick up changes and reflect them in the UI. Unfortunately, when I wrote this framework, I was not really versed into bindings, so transitioning to binding now would require a major rearchitecture, which I cannot promise can happen. Please open separate enhancement requests for both points.

**Comment by JUSTINMKAUFMAN** [comment]
Re: sorting, for the time being I'm doing this which is working well for my needs:

```
        // Sort the plist view alphabetically by key
        plistEditor.rootPropertyListNode.children = NSMutableArray(array:
            plistEditor.rootPropertyListNode.children.sortedArray(comparator: { childA, childB in
                let first = (childA as? LNPropertyListNode)?.key ?? ""
                let second = (childB as? LNPropertyListNode)?.key ?? ""
                return first.compare(second)
            }
        ))
```

**Comment by LeoNatan** [comment]
Implemented. Will release a version soon.

**Comment by LeoNatan** [comment]
2.0.5 out.
