### ISSUE TITLE
Drag and drop feature

### ISSUE THREAD

**Issue by mackie100** [LeoNatan/LNPropertyListEditor#5]
Very great work! Are you thinking of implementing drag and drop feature?

**Comment by LeoNatan** [comment]
Hello,

I haven't thought about drag and drop. I assume you mean dragging rows to reorder in an array, for example? It would be tricky to consider all corner cases; dictionaries do not support ordering, for example.

**Comment by mackie100** [comment]
> Hello,
> 
> I haven't thought about drag and drop. I assume you mean dragging rows to reorder in an array, for example? It would be tricky to consider all corner cases; dictionaries do not support ordering, for example.

All items in an outline, like a xcode plist editor. For dictionaries you could add some functionality like this https://github.com/nicklockwood/OrderedDictionary

**Comment by LeoNatan** [comment]
I’m familiar with ordered dictionaries, but not a fan. Another option is to allow usage of the internal data type directly as input if order matters.

**Comment by mackie100** [comment]
It's faster dragging items than cut and paste for reordering, also implementing find and replace functions. It would render this project complete.

**Comment by mackie100** [comment]
There are some bugs:

~1. right click on a text in key column, it makes text editable and don't fire the menu~
~2. if textfield in key column is in edit mode and if I cut that row the application crashes~

**Comment by LeoNatan** [comment]
@mackie100 Fixed the two bugs reported. Sorry, I missed your comment. In the future, please open new issues so they get better visibility.

**Comment by LeoNatan** [comment]
Drag & drop support added in 2.0.3.

**Comment by LeoNatan** [comment]
2.0.6 out with improved drag & drop support
