### ISSUE TITLE
Cannot see data type values

### ISSUE THREAD

**Issue by Tandem91** [LeoNatan/LNPropertyListEditor#6]
Data type plist values are represented by a ```<data>``` string. Is this behaviour normal? Is it related to issue #1 ?
Thanks for both the app and the framework.
[Bug-report.zip](https://github.com/LeoNatan/LNPropertyListEditor/files/4786662/Bug-report.zip)

**Comment by LeoNatan** [comment]
Hello,

This is exactly the main known limitation right now with the framework. I just haven't had time to do something better. My idea was to perhaps find some open source hex editor that has a simple programming interface and incorporate it. Perhaps something like https://github.com/ridiculousfish/HexFiend
If you are interested in submitting a PR with this functionality, that would be greatly appreciated.

I will close this issue; let's continue the discussion in #1.
