### ISSUE TITLE
I'm unable to intregrate on prefPane

### ISSUE THREAD

**Issue by cuquet** [LeoNatan/LNPropertyListEditor#7]
Hi Leo, great job!. 
I'm trying to integrate plist editor on prefPane to manage launchctl based on [Postgres-prefPane](https://github.com/MaccaTech/PostgresPrefs). As I would like to manage nginx, mariadb, postgres, ... I'd like to replace current edit view by your editor and check changes later (it's like [Launchrocket](https://github.com/jimbojsb/launchrocket) ). Drag&Drop project and include framework fails on compile.
May you help?

**Comment by LeoNatan** [comment]
Hello,
Can you please specify what the build failure is?
Thanks

**Comment by cuquet** [comment]
Hi,
I did:
Drag the LNPropertyListEditor.xcodeproj project to your project, and add LNPropertyListEditor.framework to Embedded Binaries in your project target's Generaltab. Xcode should sort everything else on its own.




and should be



Xcode output
2021-03-31 19:27:23.042707+0200 ClassroomSettingsVisibilityCheckTool[7211:2351229] [General] ClassroomSettingsVisibilityCheckTool is returning 1 (not visible)
2021-03-31 19:27:23.048431+0200 CPPrefPaneEnabledTool[7215:2351234] [CPPrefPaneEnabled] ShouldShowPrefPane: Flag file: NO
2021-03-31 19:27:23.052029+0200 AllowPasswordPref[7219:2351238] error == Error Domain=com.apple.LocalAuthentication Code=-1004 "User interaction is required." UserInfo={BiometryType=1, BiometryDatabaseHash={length = 32, bytes = 0x7b24d510 29c4256e 190eb4ba 7d2a644c ... 08d8d60c 5a2a0b9b }, AvailableMechanisms=(
    1
), NSLocalizedDescription=User interaction is required.} isSupported ==  1
2021-03-31 19:27:23.052234+0200 AllowPasswordPref[7219:2351238] Hardware Check err == 1
2021-03-31 19:27:23.052372+0200 walletAvailabilityCheckTool[7220:2351239] [Payment] PKSecureElementIsAvailable returned YES
2021-03-31 19:27:23.059251+0200 ClassKitPreferencePaneVisibilityCheckTool[7216:2351235] [default] ClassKitPreferencePane should NOT be visible
2021-03-31 19:27:23.059731+0200 AllowPasswordPref[7219:2351238] Result 0
2021-03-31 19:27:23.065562+0200 walletAvailabilityCheckTool[7220:2351239] [Payment] Cached paymentSetupSupportedInRegion returned YES
2021-03-31 19:27:23.071664+0200 System Preferences[7210:2350791]  ### AE 1868656752 sender's PID is 7210 (Preferències del Sistema)
2021-03-31 19:27:23.109426+0200 System Preferences[7210:2350791] dlopen_preflight failed with << no error >> for /Users/angel/Library/PreferencePanes/LaunchRocket.prefPane
2021-03-31 19:27:23.142758+0200 System Preferences[7210:2350791] dlopen_preflight failed with << no error >> for /Users/angel/Library/PreferencePanes/LaunchRocket.prefPane
2021-03-31 19:27:23.201647+0200 System Preferences[7210:2350791] ### advanceToConfigPhaseIfNeeded error :Error Domain=com.apple.ViewBridge Code=14 "(null)" UserInfo={com.apple.ViewBridge.error.hint={
    callStackSymbols =     (
        "0   CoreFoundation                      __exceptionPreprocess + 240",
        "1   libobjc.A.dylib                     objc_exception_throw + 60",
        "2   CoreFoundation                      _CFBundleGetValueForInfoKey + 0",
        "3   ViewBridge                          +[ViewBridgeUtilities handleFailureIn:file:lineNumber:description:] + 444",
        "4   ViewBridge                          -[NSViewServiceMarshal _bootstrap:replyData:completion:] + 2552",
        "5   ViewBridge                          -[NSViewServiceMarshal bootstrap:withReply:] + 336",
        "6   CoreFoundation                      __invoking___ + 148",
        "7   CoreFoundation                      -[NSInvocation invoke] + 448",
        "8   CoreFoundation                      -[NSInvocation invokeWithTarget:] + 80",
        "9   ViewBridge                          -[NSVB_ViewServiceImplicitAnimationDecodingProxy forwardInvocation:] + 100",
        "10  CoreFoundation                      ___forwarding___ + 736",
        "11  CoreFoundation                      _CF_forwarding_prep_0 + 96",
        "12  CoreFoundation                      __invoking___ + 148",
        "13  CoreFoundation                      -[NSInvocation invoke] + 448",
        "14  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 80",
        "15  ViewBridge                          -[NSVB_QueueingProxy forwardInvocation:] + 340",
        "16  CoreFoundation                      ___forwarding___ + 736",
        "17  CoreFoundation                      _CF_forwarding_prep_0 + 96",
        "18  CoreFoundation                      __invoking___ + 148",
        "19  CoreFoundation                      -[NSInvocation invoke] + 448",
        "20  CoreFoundation                      -[NSInvocation invokeWithTarget:] + 80",
        "21  CoreFoundation                      ___forwarding___ + 736",
        "22  CoreFoundation                      _CF_forwarding_prep_0 + 96",
        "23  CoreFoundation                      __invoking___ + 148",
        "24  CoreFoundation                      -[NSInvocation invoke] + 448",
        "25  ViewBridge                          __deferNSXPCInvocationOntoMainThread_block_invoke + 248",
        "26  ViewBridge                          __wrapBlockWithVoucher_block_invoke + 56",
        "27  ViewBridge                          __deferBlockOntoMainThread_block_invoke_2 + 432",
        "28  CoreFoundation                      __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 28",
        "29  CoreFoundation                      __CFRunLoopDoBlocks + 408",
        "30  CoreFoundation                      __CFRunLoopRun + 1732",
        "31  CoreFoundation                      CFRunLoopRunSpecific + 600",
        "32  HIToolbox                           RunCurrentEventLoopInMode + 292",
        "33  HIToolbox                           ReceiveNextEventCommon + 688",
        "34  HIToolbox                           _BlockUntilNextEventMatchingListInModeWithFilter + 76",
        "35  AppKit                              _DPSNextEvent + 868",
        "36  AppKit                              -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1312",
        "37  ViewBridge                          __75-[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:]_block_invoke + 140",
        "38  ViewBridge                          -[NSViewServiceApplication _withToxicEventMonitorPerform:] + 212",
        "39  ViewBridge                          -[NSViewServiceApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 112",
        "40  AppKit                              -[NSApplication run] + 600",
        "41  AppKit                              NSApplicationMain + 1064",
        "42  libxpc.dylib                        _xpc_objc_main + 1016",
        "43  libxpc.dylib                        _xpc_copy_xpcservice_dictionary + 0",
        "44  ViewBridge                          xpc_connection_handler + 0",
        "45  ViewBridge                          NSViewServiceApplicationMain + 512",
        "46  PreferencePanes                     PreferencePaneMain + 296",
        "47  legacyLoader-arm64                  main + 56",
        "48  libdyld.dylib                       start + 4"
    );
    name = NSInternalInconsistencyException;
    reason = "assertion failed: '<NSViewServiceMarshal: 0x12b10cad0 <NSLegacyPrefRemoteViewService: 0x6000002ac140 <(null): 0x0>>> was unable to obtain a view; the -setView: method of <NSLegacyPrefRemoteViewService: 0x6000002ac140 <(null): 0x0>> was invoked 0 times and the most recent parameter was nil' in -[NSViewServiceMarshal _bootstrap:replyData:completion:] on line 4396 of file /AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/ViewBridge/ViewBridge-551.3/NSViewServiceMarshal.m";
}, com.apple.ViewBridge.error.description=NSViewBridgeServiceBootstrapError}
2021-03-31 19:27:23.204903+0200 System Preferences[7210:2350791] ### melindro.org.LaunchRocketPrefs willSelect/willBecomeActive exception:com.apple.ViewBridge
2021-03-31 19:27:23.577631+0200 System Preferences[7210:2350791] Metal API Validation Enabled


Thanks, 
Angel

**Comment by LeoNatan** [comment]
I don't see anything related to the framework in the above log. Perhaps dynamic frameworks are not supported in preference panes?
I've made updates since. Try adding the framework using Swift Package Manager in Xcode, and link the Static variant of the framework. I just tried and it works:

<img width="780" alt="Screen Shot 2021-03-31 at 23 17 31" src="https://user-images.githubusercontent.com/2270433/113205954-83818880-9277-11eb-938d-a49fa3c51bc1.png">

**Comment by cuquet** [comment]
I have no idea swift. May you share the example? The idea is a button on prefpane which open a window view with the code on left table. 

That’s my first time with objective-c

Enviat des del meu iPhone

**Comment by LeoNatan** [comment]
Follow this:
https://github.com/LeoNatan/LNPropertyListEditor#swift-package-manager

Other than that, Google is your friend. Xcode has support for Swift Package Manager, which you can use in your project. Then link with the Static target.

**Comment by cuquet** [comment]
Thanks, I'll check it out.

El dc, 31 març 2021 a les 22:36 Leo Natan ***@***.***> va
escriure:

**Comment by LeoNatan** [comment]
👍
