### ISSUE TITLE
Undo/Redo  bug

### ISSUE THREAD

**Issue by mackie100** [LeoNatan/LNPropertyListEditor#8]
If I add, remove, copy and paste an object in an expanded item and then collapse, that object will be added or removed in a wrong location.

**Comment by LeoNatan** [comment]
Thanks, I will take a look soon.

**Comment by LeoNatan** [comment]
Fixed in 2.0.1

Thanks

**Comment by mackie100** [comment]
> Fixed in 2.0.1
> 
> Thanks

@LeoNatan thanks to you. Is there a possibility to add drag and drop functionality?

**Comment by LeoNatan** [comment]
Drag & drop support was added in 2.0.3. Enjoy

**Comment by mackie100** [comment]
> Drag & drop support was added in 2.0.3. Enjoy

Great work! I'm working how to add Find and Replace feature, but I can't find anything on the Internet.

**Comment by LeoNatan** [comment]
`NSTextFinder`, I assume, or building a custom UI. Highlighting the text would take some work.

**Comment by mackie100** [comment]
> `NSTextFinder`, I assume, or building a custom UI. Highlighting the text would take some work.

I found something interesting, but that project is in Swift code,  I'm not familiar with that language.

**Comment by LeoNatan** [comment]
It's just a language. The framework is the same.
